import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/NavBar"; // Adjust the path as needed
import Head from "next/head"; // Import Head component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/logo.png" />
      </Head>
      <body className={geistSans.variable}> {/* Use the correct font variable */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}